/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as S3StorageRouteImport } from './routes/s3-storage'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ManageAccountRouteImport } from './routes/manage-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeminiRouteImport } from './routes/gemini'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const S3StorageRoute = S3StorageRouteImport.update({
  id: '/s3-storage',
  path: '/s3-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAccountRoute = ManageAccountRouteImport.update({
  id: '/manage-account',
  path: '/manage-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeminiRoute = GeminiRouteImport.update({
  id: '/gemini',
  path: '/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gemini': typeof GeminiRoute
  '/login': typeof LoginRoute
  '/manage-account': typeof ManageAccountRoute
  '/payments': typeof PaymentsRoute
  '/permissions': typeof PermissionsRoute
  '/register': typeof RegisterRoute
  '/s3-storage': typeof S3StorageRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gemini': typeof GeminiRoute
  '/login': typeof LoginRoute
  '/manage-account': typeof ManageAccountRoute
  '/payments': typeof PaymentsRoute
  '/permissions': typeof PermissionsRoute
  '/register': typeof RegisterRoute
  '/s3-storage': typeof S3StorageRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gemini': typeof GeminiRoute
  '/login': typeof LoginRoute
  '/manage-account': typeof ManageAccountRoute
  '/payments': typeof PaymentsRoute
  '/permissions': typeof PermissionsRoute
  '/register': typeof RegisterRoute
  '/s3-storage': typeof S3StorageRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/confirm-email'
    | '/contact'
    | '/forgot-password'
    | '/gemini'
    | '/login'
    | '/manage-account'
    | '/payments'
    | '/permissions'
    | '/register'
    | '/s3-storage'
    | '/subscriptions'
    | '/reset-password/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/confirm-email'
    | '/contact'
    | '/forgot-password'
    | '/gemini'
    | '/login'
    | '/manage-account'
    | '/payments'
    | '/permissions'
    | '/register'
    | '/s3-storage'
    | '/subscriptions'
    | '/reset-password/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/confirm-email'
    | '/contact'
    | '/forgot-password'
    | '/gemini'
    | '/login'
    | '/manage-account'
    | '/payments'
    | '/permissions'
    | '/register'
    | '/s3-storage'
    | '/subscriptions'
    | '/reset-password/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GeminiRoute: typeof GeminiRoute
  LoginRoute: typeof LoginRoute
  ManageAccountRoute: typeof ManageAccountRoute
  PaymentsRoute: typeof PaymentsRoute
  PermissionsRoute: typeof PermissionsRoute
  RegisterRoute: typeof RegisterRoute
  S3StorageRoute: typeof S3StorageRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3-storage': {
      id: '/s3-storage'
      path: '/s3-storage'
      fullPath: '/s3-storage'
      preLoaderRoute: typeof S3StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-account': {
      id: '/manage-account'
      path: '/manage-account'
      fullPath: '/manage-account'
      preLoaderRoute: typeof ManageAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemini': {
      id: '/gemini'
      path: '/gemini'
      fullPath: '/gemini'
      preLoaderRoute: typeof GeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GeminiRoute: GeminiRoute,
  LoginRoute: LoginRoute,
  ManageAccountRoute: ManageAccountRoute,
  PaymentsRoute: PaymentsRoute,
  PermissionsRoute: PermissionsRoute,
  RegisterRoute: RegisterRoute,
  S3StorageRoute: S3StorageRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
